const brand = {
  navy: '#071A3D',
  blue: '#123B8A',
  blueSoft: '#DCE7FF',
  teal: '#007A70',
  tealSoft: '#C9FFF4',
  tealBright: '#7CF4E6',
  gold: '#F4C430',
  goldSoft: '#FFF2B8',
  plum: '#4B145F',
  red: '#B42318',
}

const lightScale = {
  50: '#FFFFFF',
  100: '#F6F8FC',
  200: '#EEF3FA',
  300: '#DCE7FF',
  400: '#C9D5E6',
  500: '#7D8FA8',
  600: '#50627A',
  700: '#233B5D',
  800: brand.blue,
  900: brand.navy,
  950: '#061226',
}

const redScale = {
  50: '#FEEBE9',
  100: '#FDD8D4',
  200: '#FCA8A1',
  300: '#F87171',
  400: '#EF4444',
  500: brand.red,
  600: '#991B1B',
  700: '#7F1D1D',
  800: '#63171B',
  900: '#4A1115',
  950: '#2B070A',
}

const blueScale = {
  50: '#EFF5FF',
  100: brand.blueSoft,
  200: '#BFD3FF',
  300: '#8FB1FF',
  400: '#5C88E8',
  500: '#2E5FB8',
  600: brand.blue,
  700: '#0E2E6F',
  800: brand.navy,
  900: '#061226',
  950: '#030A16',
}

const tealScale = {
  50: '#EDFFFC',
  100: brand.tealSoft,
  200: brand.tealBright,
  300: '#46D9CD',
  400: '#16B8AA',
  500: brand.teal,
  600: '#00675F',
  700: '#00534D',
  800: '#003F3A',
  900: '#002B27',
  950: '#001816',
}

const goldScale = {
  50: '#FFFBEA',
  100: brand.goldSoft,
  200: '#FFE680',
  300: brand.gold,
  400: '#D9A915',
  500: '#A77D00',
  600: '#765900',
  700: '#4D3A00',
  800: '#332600',
  900: '#211700',
  950: '#120D00',
}

const rgbVar = name => `rgb(var(${name}) / <alpha-value>)`

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: {
    relative: true,
    files: ['./index.html', './App.tsx', './index.tsx', './components/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  },
  theme: {
    fontFamily: {
      sans: ['FiraCode Nerd Font Mono', 'Fira Code', 'monospace'],
      mono: ['FiraCode Nerd Font Mono', 'Fira Code', 'monospace'],
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      white: '#FFFFFF',
      black: brand.navy,

      // Semantic UI tokens. These should be preferred in app components.
      app: rgbVar('--color-app-bg'),
      surface: rgbVar('--color-surface'),
      'surface-muted': rgbVar('--color-surface-muted'),
      'surface-strong': rgbVar('--color-surface-strong'),
      main: rgbVar('--color-text-main'),
      muted: rgbVar('--color-text-muted'),
      line: rgbVar('--color-border'),
      'line-strong': rgbVar('--color-border-strong'),
      primary: rgbVar('--color-primary'),
      'on-primary': rgbVar('--color-on-primary'),
      secondary: rgbVar('--color-secondary'),
      'on-secondary': rgbVar('--color-on-secondary'),
      accent: rgbVar('--color-accent'),
      'on-accent': rgbVar('--color-on-accent'),
      danger: rgbVar('--color-danger'),
      'on-danger': rgbVar('--color-on-danger'),
      success: rgbVar('--color-success'),
      'on-success': rgbVar('--color-on-success'),
      warning: rgbVar('--color-warning'),
      'on-warning': rgbVar('--color-on-warning'),

      // Brand scales and compatibility mappings.
      slate: lightScale,
      gray: lightScale,
      zinc: lightScale,
      neutral: lightScale,
      stone: lightScale,
      red: redScale,
      blue: blueScale,
      green: tealScale,
      emerald: tealScale,
      teal: tealScale,
      amber: goldScale,
      yellow: goldScale,
      theme: {
        surface: brand.blueSoft,
        surfaceDim: '#C9D5E6',
        surfaceBright: '#FFFFFF',
        surfaceContainerLowest: '#FFFFFF',
        surfaceContainerLow: '#F6F8FC',
        surfaceContainer: '#EEF3FA',
        surfaceContainerHigh: '#DCE7FF',
        surfaceContainerHighest: brand.goldSoft,
        onSurface: brand.navy,
        onSurfaceVariant: '#50627A',
        inverseSurface: brand.navy,
        inverseOnSurface: '#F7FAFF',
        outline: '#7D8FA8',
        outlineVariant: '#C9D5E6',
        surfaceTint: brand.blue,
        primary: brand.blue,
        onPrimary: '#FFFFFF',
        primaryContainer: brand.navy,
        onPrimaryContainer: brand.blueSoft,
        inversePrimary: brand.gold,
        secondary: brand.teal,
        onSecondary: '#FFFFFF',
        secondaryContainer: brand.tealSoft,
        onSecondaryContainer: '#002B27',
        tertiary: '#765900',
        onTertiary: '#FFFFFF',
        tertiaryContainer: brand.gold,
        onTertiaryContainer: '#211700',
        error: brand.red,
        onError: '#FFFFFF',
        errorContainer: '#FEEBE9',
        onErrorContainer: '#7F1D1D',
        primaryFixed: brand.blueSoft,
        primaryFixedDim: '#BFD3FF',
        onPrimaryFixed: brand.navy,
        onPrimaryFixedVariant: brand.blue,
        secondaryFixed: brand.tealBright,
        secondaryFixedDim: '#46D9CD',
        onSecondaryFixed: '#002B27',
        onSecondaryFixedVariant: '#00534D',
        tertiaryFixed: brand.gold,
        tertiaryFixedDim: '#D9A915',
        onTertiaryFixed: '#211700',
        onTertiaryFixedVariant: '#4D3A00',
        background: '#F6F8FC',
        onBackground: brand.navy,
        surfaceVariant: '#DCE7FF',
      },
      'theme-yellow': brand.gold,
      'theme-teal': brand.tealBright,
      'theme-red': brand.red,
      'theme-maroon': brand.navy,
      'theme-black': brand.navy,
      'dark-bg': '#061226',
      'dark-card': '#0B1E3A',
    },
  },
}
