const corporateTechColors = {
  surface: '#fff7fa',
  surfaceDim: '#fccaff',
  surfaceBright: '#fff7fa',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#ffeffb',
  surfaceContainer: '#ffe7fd',
  surfaceContainerHigh: '#ffdefe',
  surfaceContainerHighest: '#fed6ff',
  onSurface: '#350040',
  onSurfaceVariant: '#444651',
  inverseSurface: '#560068',
  inverseOnSurface: '#ffebfc',
  outline: '#757682',
  outlineVariant: '#c5c5d3',
  surfaceTint: '#4059aa',
  primary: '#00236f',
  onPrimary: '#ffffff',
  primaryContainer: '#1e3a8a',
  onPrimaryContainer: '#90a8ff',
  inversePrimary: '#b6c4ff',
  secondary: '#006a61',
  onSecondary: '#ffffff',
  secondaryContainer: '#86f2e4',
  onSecondaryContainer: '#006f66',
  tertiary: '#6f5d00',
  onTertiary: '#ffffff',
  tertiaryContainer: '#c6aa23',
  onTertiaryContainer: '#4b3f00',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  primaryFixed: '#dce1ff',
  primaryFixedDim: '#b6c4ff',
  onPrimaryFixed: '#00164e',
  onPrimaryFixedVariant: '#264191',
  secondaryFixed: '#89f5e7',
  secondaryFixedDim: '#6bd8cb',
  onSecondaryFixed: '#00201d',
  onSecondaryFixedVariant: '#005049',
  tertiaryFixed: '#ffe262',
  tertiaryFixedDim: '#e3c53f',
  onTertiaryFixed: '#221b00',
  onTertiaryFixedVariant: '#534600',
  background: '#fff7fa',
  onBackground: '#350040',
  surfaceVariant: '#fed6ff',
}

const lightScale = {
  50: corporateTechColors.surfaceContainerLowest,
  100: corporateTechColors.surfaceContainerLow,
  200: corporateTechColors.surfaceContainer,
  300: corporateTechColors.surfaceContainerHigh,
  400: corporateTechColors.outlineVariant,
  500: corporateTechColors.outline,
  600: corporateTechColors.onSurfaceVariant,
  700: corporateTechColors.onSurface,
  800: corporateTechColors.inverseSurface,
  900: corporateTechColors.primary,
  950: corporateTechColors.onPrimaryFixed,
}

const redScale = {
  50: corporateTechColors.errorContainer,
  100: corporateTechColors.errorContainer,
  200: corporateTechColors.errorContainer,
  300: corporateTechColors.errorContainer,
  400: corporateTechColors.error,
  500: corporateTechColors.error,
  600: corporateTechColors.error,
  700: corporateTechColors.onErrorContainer,
  800: corporateTechColors.onErrorContainer,
  900: corporateTechColors.onErrorContainer,
  950: corporateTechColors.onErrorContainer,
}

const blueScale = {
  50: corporateTechColors.primaryFixed,
  100: corporateTechColors.primaryFixed,
  200: corporateTechColors.primaryFixedDim,
  300: corporateTechColors.inversePrimary,
  400: corporateTechColors.onPrimaryContainer,
  500: corporateTechColors.surfaceTint,
  600: corporateTechColors.primaryContainer,
  700: corporateTechColors.primary,
  800: corporateTechColors.onPrimaryFixedVariant,
  900: corporateTechColors.onPrimaryFixed,
  950: corporateTechColors.onPrimaryFixed,
}

const greenScale = {
  50: corporateTechColors.secondaryFixed,
  100: corporateTechColors.secondaryFixed,
  200: corporateTechColors.secondaryContainer,
  300: corporateTechColors.secondaryFixedDim,
  400: corporateTechColors.secondaryFixedDim,
  500: corporateTechColors.secondary,
  600: corporateTechColors.secondary,
  700: corporateTechColors.onSecondaryFixedVariant,
  800: corporateTechColors.onSecondaryFixed,
  900: corporateTechColors.onSecondaryFixed,
  950: corporateTechColors.onSecondaryFixed,
}

const yellowScale = {
  50: corporateTechColors.tertiaryFixed,
  100: corporateTechColors.tertiaryFixed,
  200: corporateTechColors.tertiaryFixed,
  300: corporateTechColors.tertiaryFixedDim,
  400: corporateTechColors.tertiaryContainer,
  500: corporateTechColors.tertiaryContainer,
  600: corporateTechColors.tertiary,
  700: corporateTechColors.onTertiaryFixedVariant,
  800: corporateTechColors.onTertiaryFixed,
  900: corporateTechColors.onTertiaryFixed,
  950: corporateTechColors.onTertiaryFixed,
}

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: {
    relative: true,
    files: ['./index.html', './App.tsx', './index.tsx', './components/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  },
  theme: {
    fontFamily: {
      sans: ['FiraCode Nerd Font Mono', 'Fira Code', 'monospace'],
      mono: ['FiraCode Nerd Font Mono', 'Fira Code', 'monospace'],
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      white: corporateTechColors.surfaceContainerLowest,
      black: corporateTechColors.onSurface,
      slate: lightScale,
      gray: lightScale,
      zinc: lightScale,
      neutral: lightScale,
      stone: lightScale,
      red: redScale,
      blue: blueScale,
      green: greenScale,
      emerald: greenScale,
      amber: yellowScale,
      yellow: yellowScale,
      theme: corporateTechColors,
      'theme-yellow': corporateTechColors.tertiaryFixed,
      'theme-teal': corporateTechColors.secondaryFixed,
      'theme-red': corporateTechColors.error,
      'theme-maroon': corporateTechColors.inverseSurface,
      'theme-black': corporateTechColors.onSurface,
      'dark-bg': corporateTechColors.inverseSurface,
      'dark-card': corporateTechColors.primary,
    },
  },
}
